### ISSUE TITLE
Check for psresourceget before installing

### ISSUE THREAD

**Issue by mgreenegit** [natescherer/devcontainers-custom-features#16]
Just heads-up, [psresourceget is in 7.4 (preview)](https://github.com/PowerShell/PowerShell/blob/aa31732aa94c52605d28822215f889ca3174d850/CHANGELOG/preview.md?plain=1#L39).

So [install.ps1](https://github.com/natescherer/devcontainers-custom-features/blob/6832f70b05e0fb7e0acdd492c7306ad5ea172572/src/powershell-resources/install.ps1#L5
) could begin checking for the module before running install-module.

**Comment by natescherer** [comment]
Good callout! This will be included in the next version that will hopefully go out this week.

**Comment by natescherer** [comment]
This is fixed in 1.1.0 that just went out!
